// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdrqyrbxajmptwlbnhet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkcnF5cmJ4YWptcHR3bGJuaGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjUyNjcsImV4cCI6MjA3MDUwMTI2N30.43Fu_GdsPhShrz15mz3hvUfUFbmJXYK2XEVng-d6uwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});